### PR TITLE
'Recommended video' block + alphabetical refactor

### PR DESCRIPTION
**Pull request by OxrxL**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please explain the motivation of this PR

**Comment by OxrxL** [comment]
> Please explain the motivation of this PR

Already explained here:

https://github.com/revanced/revanced-patches/issues/109

**Comment by oSumAtrIX** [comment]
Please always link issues to PRs. Also theres unrelated lines changed.

**Comment by OxrxL** [comment]
> Please always link issues to PRs. Also theres unrelated lines changed.

I linked it after PR open...and relinked it after your question. :D

**Comment by oSumAtrIX** [comment]
You have to link it before opening the PR as ready. Also still lots of unrelated lines changed. Reopen this PR with only the relevant lines changed or add a new commit fixing it.

**Pull request closed without merging**
