### PR TITLE
feat: `swipe-controls` rewrite

### PR DESCRIPTION
**Pull request by shadow578**
Basically a full rewrite of the `swipe-controls` i submitted previously, that should fix most (if not all) issues of the original implementation
- Press-to-Swipe (the feature where you had to long-press before swiping) can be disabled (disabled by default)
- YouTube Gestures working normally
   - double- tap to seek
   - horizontal swipe to seek 
   - pinch to zoom
   - recommendations in fullscreen mode \*
   - swipe to exit fullscreen \*
- only two hooks needed (so robust against changes in the base app)
- (imho) cleaner code
- ...

> \* only **with** PtS 

## TODOs (will update later):
- [X] remove references to `fenster`, refactor to 'swipe-controls`
- [X] config options for overlay timeout & haptic feedback
- [X] nicer overlay ui
- [X] update patch

BTW, is there somewhere were the development is coordinated? It's kinda annoying coming back after making some bigger changes and having catch up on tons of tiny monkey- patches...

### CODE REVIEW

**Comment by TheJeterLP** [comment]
> BTW, is there somewhere were the development is coordinated? It's kinda annoying coming back after making some bigger changes and having catch up on tons of tiny monkey- patches...

No, because this project is open source. When someone wants to change something, they can do that. If you want to change your own work (e.g. Bugfixes, refactoring, etc), please create an issue first before creating the PR so people know that you're working on it and don't start to create their own fixes :) 

Other patches etc are always being created and merged.

Anyways, thank you so much for this big contribution!

**Comment by shadow578** [comment]
> No, because this project is open source. When someone wants to change something, they can do that. If you want to change your own work (e.g. Bugfixes, refactoring, etc), please create an issue first before creating the PR so people know that you're working on it and don't start to create their own fixes :)

Yes, i do know that since this is an open- source project, there'll be many people working on it. 
I was just wondering, since i haven't contributed to many projects before. 

So the right way to do this would be to first create an issue (something along the lines of 'this does not work, but i'll fix it soon please wait'), and then when i open the PR mention that issue? 

Also, is there a document somewhere to see what the 'Semantic-PR' check wants to see in the title?

**Comment by TheJeterLP** [comment]
>Also, is there a document somewhere to see what the 'Semantic-PR' check wants to see in the title? 

Yes, look at this: https://www.conventionalcommits.org/en/v1.0.0/#summary

Currently you can use fix, feat and refactor. Altho you should keep in mind that refactor does not trigger a new release, so for your case only fix and feat would apply.

**Comment by TheJeterLP** [comment]
Current known issues are:
https://github.com/revanced/revanced-patches/issues/124
https://github.com/revanced/revanced-patches/issues/127
https://github.com/revanced/revanced-patches/issues/128

**Comment by TheJeterLP** [comment]
Are you on the discord server btw?

**Comment by shadow578** [comment]
> Are you on the discord server btw?

yes as 'shadow578#6488', although i'm not really active on discord

**Comment by oSumAtrIX** [comment]
We talk lots on Discord, if you like to join us at https://revanced.app/discord

**Comment by TheJeterLP** [comment]
> We talk lots on Discord, if you like to join us at https://revanced.app/discord

Hes already on it. joined in may

**Comment by OxrxL** [comment]
@shadow578 A nicer UI

7BA538FA-142B-4B80-BD3E-C1F800624CBB

**Comment by shadow578** [comment]
> The nicer overlay UI

actually thought of something similar too, but that could be kinda difficult to pull off...
maybe i'll just add a icon or two to replace the text for the time being, and expand on it later

**Comment by shadow578** [comment]
new ui is done (mainly just used icons instead of text, nothing too fancy) + some bug fixes, will test a bit more then ready the PR tomorrow

image

**Comment by OxrxL** [comment]
> new ui is done (mainly just used icons instead of text, nothing too fancy) + some bug fixes, will test a bit more then ready the PR tomorrow
> 
> image

Agree. Minimalistic is better.

P.S: Can you make it a bit bigger?

**Comment by oSumAtrIX** [comment]
> P.S: Can you make it a bit bigger?

Stuff like this should be controlled via a setting, such as size, opacity, roundness, and hidden/visible

**Comment by shadow578** [comment]
> Stuff like this should be controlled via a setting, such as size, opacity, roundness, and hidden/visible

added some options to customize size and color. At the moment, `SettingsEnum` does not support ARGB colors, so i limited the setting to background alpha only. But everything is in place for abominations like this:

image

**Comment by EXAM454** [comment]
> > Stuff like this should be controlled via a setting, such as size, opacity, roundness, and hidden/visible
> 
> added some options to customize size and color. At the moment, `SettingsEnum` does not support ARGB colors, so i limited the setting to background alpha only. But everything is in place for abominations like this:
> 
> image

also add a option of position of volume , brightness text such as middle of screen or top of screen. if that icon&text placed top of screen then it will not block the view of video.

**Comment by TheJeterLP** [comment]
Awesome. Don't forget to add the settings in the resources

**Comment by TheJeterLP** [comment]
Is this ready?

**Comment by fillwithjoy1** [comment]
> Current known issues are: [ReVanced/revanced-patches#124](https://github.com/ReVanced/revanced-patches/issues/124) [ReVanced/revanced-patches#127](https://github.com/ReVanced/revanced-patches/issues/127) [ReVanced/revanced-patches#128](https://github.com/ReVanced/revanced-patches/issues/128)

#127 issue is still not resolved, please look into this

**Comment by oSumAtrIX** [comment]
This PR isn't supposed to solve #127. Please don't spam the repositories, I've told you already that they were closed for not meeting the acknowledgements multiple times now

**Comment by fillwithjoy1** [comment]
> This PR isn't supposed to solve #127. Please don't spam the repositories, I've told you already that they were closed for not meeting the acknowledgements multiple times now

How is what I'm doing considered as spam? I cannot make an issue for age restriction because ReVanced/revanced-patches#127 exists now, therefore making it impossible for anyone to make an issue about this. That's why I'm raising about this issue because nobody has done anything about it. If you have something else in mind then let me know

**Pull request merged**
