### PR TITLE
fix(YouTube - Hide layout components): Hide search result shelf header

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
Closes [#8](https://github.com/ReVanced/revanced-patches/issues/8)

### CODE REVIEW

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
Compact channel hides channels in some places like search the last time I saw it. I think it also only happens in tablet mode

**Comment by ILoveOpenSourceApplications** [comment]
This is how the header looks currently:
Screenshot_20240828_233918_YouTube

**Comment by ILoveOpenSourceApplications** [comment]
They have merged the header with the channel profile, basically making into one. If needed then the name of the patch can be changed accordingly.

**Comment by ILoveOpenSourceApplications** [comment]
Maybe something like `Hide channel profile in search results`?

**Comment by ILoveOpenSourceApplications** [comment]
A more user-centric approach would be to present users with a choice while also allowing users to determine their preference which would enhance the overall user experience.

**Comment by oSumAtrIX** [comment]
With PR https://github.com/ReVanced/revanced-patches/pull/3462, ReVanced Integrations has been merged into ReVanced Patches. This PR must be reopened in the [ReVanced Patches](https://github.com/ReVanced/revanced-patches) repository and adjusted to the new build system. ReVanced Integration is now understood as "extensions" according to the ReVanced Patcher API. As extensions are now on a per-patch basis, this PR may be subject to a separate extension. If not, the PR can change the shared extension in [ReVanced Patches](https://github.com/ReVanced/revanced-patches).

Thanks, for the PR.

**Pull request closed without merging**
