### PR TITLE
feat(youtube): `double-back-to-close` patch

### PR DESCRIPTION
**Pull request by inotia00**
Make it possible to close the app by double-pressing the back button in the home feed

Also, it solves this issue https://github.com/revanced/revanced-patches/issues/615

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Why should one want to press back two times when they can just press the home button to exit the app?

**Comment by Kalpataru6** [comment]
People who use 3 button navigation need it..

**Comment by inotia00** [comment]
there is no particular reason
It's just that when I first conceived this, I wanted to implement it as a feature that closes the app with a double tap.

If the home button can replace the role of the back button, there is no need for this PR.

**Comment by Kalpataru6** [comment]
As you said there is no particular reason to do anything but functionality will be good.. I'm fine how it is now but my father always use back button and I can't for the love of God change his habit of back tapping to home button tapping.. If this implemented people like my father will be grateful.

**Comment by oSumAtrIX** [comment]
The home button replaces the role of the back button. Your father would change his habit regardless of this PR because it only adds the feature to exit by swiping back twice.

**Comment by Kalpataru6** [comment]
Oh ok.. But is there any way to solve the 3 button navigation 's back button issue?

**Comment by oSumAtrIX** [comment]
Yes, by clicking the home button you can exit the app just like any other app.

**Comment by 0xrxL** [comment]
> Your father would change his habit

Apple style 😂

**Comment by inotia00** [comment]
If so.. this PR is not necessary

**Pull request closed without merging**
