### PR TITLE
fix: pull up to refresh

### PR DESCRIPTION
**Pull request by OxrxL**
Still need to be tested further, to be sure it always works.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Nothing is being added to the new array, what is the plan?

**Comment by OxrxL** [comment]
> Nothing is being added to the new array, what is the plan?

The plan is to replace the string called "value" with the bytebuffer. In this way we should be able to block literally everything related to ads elements (also the empty containers that "value" variable can't detect).

**Comment by oSumAtrIX** [comment]
Îs `value` still required? If not, please remove it.

**Comment by OxrxL** [comment]
Obviously we need to keep "value" variable for searching further new ads. It's better of bytebuffer for debug.

**Comment by dibyarupprk** [comment]
It doesn't work, still pull down to refresh is buggy

**Pull request merged**
