### PR TITLE
fix: remove long-press from swipe-controls

### PR DESCRIPTION
**Pull request by EXAM454**
vanced style swipe volume and brightness, no need to longpress. perfectly compatable with patches 2.9.1.

### CODE REVIEW

**Comment by TheJeterLP** [comment]
Also please reopen the PR in the patches repo

**Comment by TheJeterLP** [comment]
Also the patch still does nothing for me on yt 17.25.34.

**Comment by EXAM454** [comment]
> Also the patch still does nothing for me on yt 17.25.34.

yes its's works. first add comapatibility on compatibility.kt

**Comment by TheJeterLP** [comment]
> > Also the patch still does nothing for me on yt 17.25.34.
> 
> yes its's works. first add comapatibility on compatibility.kt

Yes just tested it. I'll add the compatibility

**Comment by EXAM454** [comment]
> > > Also the patch still does nothing for me on yt 17.25.34.
> > 
> > 
> > yes its's works. first add comapatibility on compatibility.kt
> 
> Yes just tested it. I'll add the compatibility
        "com.google.android.youtube", arrayOf("17.24.34","17.25.34")

**Comment by TheJeterLP** [comment]
> > > > Also the patch still does nothing for me on yt 17.25.34.
> > > 
> > > 
> > > yes its's works. first add comapatibility on compatibility.kt
> > 
> > 
> > Yes just tested it. I'll add the compatibility
> > "com.google.android.youtube", arrayOf("17.24.34","17.25.34")

Please open a new PR for the patches repo with the addition of the 17.25.34 version so I can merge the patch again.

**Pull request merged**
