### PR TITLE
refactor: move settings to SettingsEnum

### PR DESCRIPTION
**Pull request by TheJeterLP**
See https://github.com/revanced/revanced-integrations/issues/37

### CODE REVIEW

**Comment by OxrxL** [comment]
@TheJeterLP why you add "text_display_ad_with_themed_cta_banner_image"?

It should be already blocked by "ad_" generic reference (placed at the top of list).

It's checked by a contains istruction, should be good already.

**Comment by TheJeterLP** [comment]
> @TheJeterLP why you add "text_display_ad_with_themed_cta_banner_image"?
> 
> It should be already blocked by "ad_" generic reference (placed at the top of list).
> 
> It's checked by a contains istruction, should be good already. 🤷‍♂️

Was just for debugging. Forgot to remove it from commit.

**Comment by OxrxL** [comment]
> > @TheJeterLP why you add "text_display_ad_with_themed_cta_banner_image"?
> > It should be already blocked by "ad_" generic reference (placed at the top of list).
> > It's checked by a contains istruction, should be good already. 🤷‍♂️
> 
> Was just for debugging. Forgot to remove it from commit.

Anyway...have you understand how to block new elements? Was not much difficult at the end xD.

**Comment by OxrxL** [comment]
> > > > @TheJeterLP why you add "text_display_ad_with_themed_cta_banner_image"?
> > > > It should be already blocked by "ad_" generic reference (placed at the top of list).
> > > > It's checked by a contains istruction, should be good already. 🤷‍♂️
> > > 
> > > 
> > > Was just for debugging. Forgot to remove it from commit.
> > 
> > 
> > Anyway...have you understand how to block new elements? Was not much difficult at the end xD.
> 
> Yes, also implemented a log for that.

Good. This will be useful for future (eventually) new ads. 👍

**Pull request merged**
