### PR TITLE
feat(Youtube/GeneralAds): `hide-music-section` in description

### PR DESCRIPTION
**Pull request by johnconner122**
**Before:**
PicB
**After:**
PicA

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Why would one want that removed?

**Comment by johnconner122** [comment]
> Why would one want that removed? 

I don't know. Maybe, the same reason they wanna remove comments section, or chapter teaser, or channel bar. 🤷

**Comment by oSumAtrIX** [comment]
The comments section was justified with the probability of containing spoiler, the chapter teaser originally obstructed the search results with  
unnecessary addition of wasted space, the channel bar might be interesting for people who don't care about subscription or details to the creator, this PR on the other hand, doesn't remove anything which obstructs usage

**Comment by johnconner122** [comment]
> The comments section was justified with the probability of containing spoiler, the chapter teaser originally obstructed the search results with  
> unnecessary addition of wasted space, the channel bar might be interesting for people who don't care about subscription or details to the creator, this PR on the other hand, doesn't remove anything which obstructs usage

Fine as you see fit.

**Comment by oSumAtrIX** [comment]
That section is quite useful and essential to music videos, which is why I'll close this PR for now. Make sure to open an issue for discussion before working on something, thanks!

**Pull request closed without merging**
