### PR TITLE
Change that auto skipped will only trigger once per segment

### PR DESCRIPTION
**Pull request by thebestnom**
Should work, now testing

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Is this WIP as the title suggests, if so please mark this PR as a draft.

**Comment by thebestnom** [comment]
Sorry, for some reason thought that writing [WIP] will auto draft it 😅 (it should work like that, but I do want to test first)

**Comment by thebestnom** [comment]
Ok, it half works, it does allow to watch second time, but the skip button doesn't work...will complete this tomorrow

**Comment by thebestnom** [comment]
Ok, now first skip works and skip button does work on second time, but overlapping segment it skips only the first segment

**Comment by thebestnom** [comment]
Ok, now it works

**Comment by oSumAtrIX** [comment]
Can you explain all changes and the new behaviour?

**Comment by thebestnom** [comment]
The new behavior is that if a segment did auto skipped, it will do it just once, so if you go back to the same segment now the skip button will be there instead of skipping

The changes are that now segment object have a skipped property to save if it already did auto skipped
Than the skip button will check if the skip and that it didn't auto skipped to see if it needed to be shown
And added that the skip function will return if it succeed or not so I could check if the segment did actually skipped or not so it could put the auto skipped  property correctly only if it did skip

**Comment by thebestnom** [comment]
example
https://user-images.githubusercontent.com/21955247/198844214-4eb4652e-5826-4fea-9e21-848d37ec75fd.mp4

**Comment by oSumAtrIX** [comment]
If possible, can you add a settings switch which enables back the defaut behaviour? Something like "Skip once". If the switch is turned off (by default it should be on), then it will skip the segment every time.

**Comment by thebestnom** [comment]
Can try, but didn't touch patches ever so it would take me more time 😅 (but if Ill do I will do that you could enable it per segment type)

**Comment by oSumAtrIX** [comment]
You would only need to make changes to the integrations.
RE: https://github.com/revanced/revanced-integrations/blob/d745e293953e61f01970ccdc6937572e25744146/app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockSettings.java#L99

**Comment by thebestnom** [comment]
Works but the string is skip_automattically_once, how do we add to strings?

**Comment by thebestnom** [comment]
Added string to patcces, didn't test

**Comment by thebestnom** [comment]
I did test the new enum and it works, didn't test the strings.xml patch

**Comment by thebestnom** [comment]
https://github.com/revanced/revanced-patches/pull/907 Works

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
Thanks

**Pull request merged**
