### PR TITLE
fix: some more refactoring and cleanup

### PR DESCRIPTION
**Pull request by TheJeterLP**
PR is named fix so a new version gets generated

Needs to be merged together with https://github.com/revanced/revanced-patches/pull/63

### CODE REVIEW

**Comment by OxrxL** [comment]
@TheJeterLP Technically you could remove VP9 codec override (with model override too), due to features deprecation.

At least based on what @oSumAtrIX said.

**Comment by TheJeterLP** [comment]
> @TheJeterLP Technically you could remove VP9 codec override (with model override too), due to features deprecation.
> 
> At least based on what @oSumAtrIX said.

@oSumAtrIX can you confirm that this doesn't work anymore?

**Comment by oSumAtrIX** [comment]
I never claimed that.

**Comment by OxrxL** [comment]
> I never claimed that.

Well...maybe was I my mistake.

Also if I remember that from an old private discussion. 🤷‍♂️

**Pull request merged**
