### PR TITLE
refactor: move settings to SettingsEnum class

### PR DESCRIPTION
**Pull request by TheJeterLP**
See https://github.com/revanced/revanced-integrations/issues/37

### CODE REVIEW

**Comment by OxrxL** [comment]
Based on @oSumAtrIX decision, this litho block should be removed because it disable comments (even if I would like it to keep it):

```
private static boolean isExperimentalCommentsRemoval() {
        return getBoolean("experimental_comments", false);
}
```

**Comment by oSumAtrIX** [comment]
No, it should not be removed.

**Comment by TheJeterLP** [comment]
> Based on @oSumAtrIX decision, this litho block should be removed because it disable comments (even if I would like it to keep it):
> 
> ```
> private static boolean isExperimentalCommentsRemoval() {
>         return getBoolean("experimental_comments", false);
> }
> ```

Makes no sense to remove a feature when theres a setting for it to toggle it.

**Comment by OxrxL** [comment]
> Makes no sense to remove a feature when theres a setting for it to toggle it.

I agree. Maybe he re-evaluated his decision.

**Comment by oSumAtrIX** [comment]
But I never said to remove it

**Comment by OxrxL** [comment]
> But I never said to remove it

Troll?
Immagine 2022-07-03 223922

**Comment by oSumAtrIX** [comment]
The image is out of context. This was my next response:
image

**Comment by OxrxL** [comment]
> The image is out of context. This was my next response (missing the "not" in the sentence): image

Sorry, I hadn't paid attention to this comment.👍

Anyway, to close this OT, I'll push some other stuff to hide other comments.

**Comment by oSumAtrIX** [comment]
Create a patch suggestion on the ReVanced organization discussion page, and see if people need it, before adding it. If you insist, simply make it optional and disabled by default.

**Comment by OxrxL** [comment]
> Create a patch suggestion on the ReVanced organization discussion page, and see if people need it, before adding it. If you insist, simply make it optional and disabled by default.

Again sorry.

**Comment by oSumAtrIX** [comment]
> > Create a patch suggestion on the ReVanced organization discussion page, and see if people need it, before adding it. If you insist, simply make it optional and disabled by default.
> 
> Again sorry.

No worries :) Thanks for contributing!

**Pull request closed without merging**
