### PR TITLE
fix(YouTube - Client Spoof): Unlock more qualities by spoofing the iOS client user agent 

### PR DESCRIPTION
**Pull request by zainarbani**
Integrations for: [ReVanced/revanced-patches#3468](https://github.com/ReVanced/revanced-patches/pull/3468)

### CODE REVIEW

**Comment by 0xrxL** [comment]
@zainarbani Some useful links to update client version:

[iOS](https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664) - Last: 19.29.1

[VR](https://www.meta.com/experiences/2002317119880945/) - Last: 1.58.14

**Comment by OxrxL** [comment]
> The VR version acts up when using older/newer versions (particularly with live streams).
> 
> Unless changing the version is shown to fix limitations, it's better to keep using the current versions.

Same thing for iOS?

**Comment by zainarbani** [comment]
@0xrxL Can you try this patch and see wether HDR uses AV01 or VP9.2? (you can use my forks build)

**Comment by 0xrxL** [comment]
> @0xrxL Can you try this patch and see wether HDR uses AV01 or VP9.2? (you can use my forks build)

Only AV1 unlock HDR:

Screenshot_20240725_085813_YouTube

Screenshot_20240725_085752_YouTube

**Comment by oSumAtrIX** [comment]
Does iOS play HDR vp9 streams

**Comment by 0xrxL** [comment]
> Does iOS play HDR vp9 streams

If it's a question: nope, at least in my case. iOS spoof can just play HDR videos with av01 codec.

**Comment by zainarbani** [comment]
> Does iOS play HDR vp9 streams

It play vp9 HDR starting from iOS 14

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
