### PR TITLE
refactor: integrations

### PR DESCRIPTION
**Pull request by TheJeterLP**
Complete refactor for the Integrations classes from original Vanced.
This does:

- [x] Sort all classes with package names
- [x] Rename some classes to make it easier to understand what they do (ex. XGlobals is actually a Settings file)
- [x] Remove Classes that do the same thing
- [x] Remove Classes that do absolutely nothing and are nowhere used
- [x] Start creating API methods that are called by the patches. See [patches](https://github.com/TheJeterLP/revanced-integrations/tree/dev/app/src/main/java/app/revanced/integrations/patches) for that.
- [x] Reformatting code for readability
- [x] Implement LogHelper class to automatically check for debug settings when using debug log.
- [x] Stop direct accesing settings variables in Settings class (former XGlobals) and use an enum now for accessing settings. 
- [x] Make own classes that are used by the patches similar to an actual API. Logic can be changed now without breaking code. 

Still some work ToDo, but this should be merged now so devs working on patches currently don't have to do their work twice. Is at its current stage completely usable. 

**NEEDS TO BE MERGED TOGETHER WITH [revanced-patches#44](https://github.com/revanced/revanced-patches/pull/44)**

See https://github.com/revanced/revanced-integrations/issues/16 for the regarding issue

### CODE REVIEW

**Comment by TheJeterLP** [comment]
See https://github.com/revanced/revanced-integrations/issues/16

**Comment by Sculas** [comment]
Are you familiar with Kotlin? If so, feel free to start converting classes to Kotlin, if you want to. 🙂

**Comment by TheJeterLP** [comment]
> Are you familiar with Kotlin? If so, feel free to start converting classes to Kotlin, if you want to. 🙂

Sadly I am not :(

**Comment by TheJeterLP** [comment]
> > but this should be merged now so devs working on patches currently don't have to do their work twice
> 
> Git will handle the merge conflicts. This PR should be finished before merging to `main`.

Its ready now. Fixed all the merge conflicts

**Comment by oSumAtrIX** [comment]
> Remove Classes that do absolutely nothing and are nowhere used

Did you consider that patches might depend on them which have not yet been implemented?

**Comment by TheJeterLP** [comment]
> > Remove Classes that do absolutely nothing and are nowhere used
> 
> Did you consider that patches might depend on them which have not yet been implemented?

Yes I did, those were just helper classes that are now merged together

**Pull request merged**
