### PR TITLE
fix(youtube/sponsorblock): Include milliseconds in the voting menu

### PR DESCRIPTION
**Pull request by sebm253**
Milliseconds are essential for SponsorBlock segments.

### CODE REVIEW

**Review by oSumAtrIX — COMMENTED** [review]
Have you checked if the step size is in the milliseconds?

**Comment by caneleex** [comment]
I'm not quite sure what you mean

**Comment by oSumAtrIX** [comment]
You just changed the formatting, but does the UI allow to select timestamps in the milliseconds range?

**Comment by caneleex** [comment]
yes, both on (re)vanced and in the desktop extension - otherwise skips would be terrible

**Pull request merged**
