### PR TITLE
fix(YouTube - Spoof client): Disable AV1 if not supported by spoofing an older iOS device

### PR DESCRIPTION
**Pull request by LisoUseInAIKyrios**
Change iOS device to iPhone XS Max, to (maybe/probably) reduce the chance of using AV1 streams.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Don't devices that support AV1 profit of these streams?

**Review by oSumAtrIX — APPROVED** [review]

**Comment by oSumAtrIX** [comment]
@sodawithoutsparkles

**Comment by SodaWithoutSparkles** [comment]
My phone has a Dimensity 8100 which supports AV1 decode according to the manufacturer's site. This could maybe solve some of the issues. 

I've also identified a few other possible causes for the stuttering. I'll now use the stats for nerds feature on every video now to see if I could identify some trends.

I can test this next morning with CLI, I still need to test the other issue at patches/3238

P.S. I wonder if the `deviceHasAV1HardwareDecoding` func passes if the device only supports decode not encode. I might be wrong here, but it seems that it just checks if it has either decode or encode?

**Comment by SodaWithoutSparkles** [comment]
I was still getting avc1. Now starting ADB to check the logs

**Comment by SodaWithoutSparkles** [comment]
From logcat I can see that it did detect that my phone supports AV1 hardware decode: 

```shell
05-29 17:45:05.475 22902 23020 D revanced: SpoofClientPatch: Device supports AV1 hardware decoding.
```

Nevertheless it is still using format 299 (avc1 1920x1080@60) when using [this video](https://youtu.be/njX2bu-_Vw4) as a test. It is not only limited to this video tho, all videos are still avc1.

**Comment by SodaWithoutSparkles** [comment]
It works as intended then

**Pull request merged**
