### PR TITLE
Minimal misc changes to improve developments

### PR DESCRIPTION
**Pull request by YonLiud**

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
10/10 PR

**Comment by Relected** [comment]
that's actually pretty cool

**Comment by baiorett** [comment]
this is a useless contribution

**Comment by Lucaskyy** [comment]
@baiorett Watch your words next time, thank you.

**Comment by baiorett** [comment]
> @baiorett Please act respectfully, thank you.

i mean, in which way this improves development

**Comment by Lucaskyy** [comment]
Even if you find this contribution "useless", you act respectfully and professionally. Every contribution has value.

**Review by baiorett — COMMENTED** [review]
-

**Comment by YonLiud** [comment]
> again, i don't see any reason in this small change because the user will not even see that because integrations are not meant to be run but built

it's not to help the end-user, it's to help other developers like you to debug incase of a problem

**Comment by baiorett** [comment]
> > again, i don't see any reason in this small change because the user will not even see that because integrations are not meant to be run but built
> 
> it's not to help the end-user, it's to help other developers like you to debug incase of a problem

the debugging is handled in gradle itself, not in the batch scripts that initialize gradle

**Comment by lewis1277** [comment]
> again, i don't see any reason in this small change because the user will not even see that because integrations are not meant to be run but built

Only thinking of the end-user? tut tut tut

**Comment by ReduxFlakes** [comment]
This should be implemented

**Comment by Lucaskyy** [comment]
Thank you for this PR!

**Comment by ponces** [comment]
The renaming of the gradlew script does not make sense and it's not coherent with the other revanced repos.

> that's actually pretty good, the gradlew.sh file should make it easier for Linux users to recognize the files

Gradle Linux users know that gradlew is the script to handle gradle tasks...

Please revert this part of the PR :(

**Comment by oSumAtrIX** [comment]
I agree to @ponces

**Comment by ArjixWasTaken** [comment]
Objection!

I would think that a file without a file extension is a binary file, so I wouldn't try to execute it.
But since @Lucaskyy renamed it to have the .sh extension it is now obvious that it is a script we can execute through the command line.

As for it not being coherent with the other repos, that's a skill issue.

**Comment by Lucaskyy** [comment]
> Objection!

Hearsay!

Sorry, watched too many Johnny Depp vs Amber Heard videos.

**Comment by tillnelown** [comment]
Why not remove the '.sh' and instead give the file executable permission? This highlights the file and shows everyone which file to execute through ls and so on.

**Pull request merged**
