### PR TITLE
fix: ads block

### PR DESCRIPTION
**Pull request by OxrxL**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Is this tested and confirmed?

**Comment by OxrxL** [comment]
> Is this tested and confirmed?

Still not...leave it open until my confirmation.

Thanks

**Comment by oSumAtrIX** [comment]
Create a draft PR and when it is done you can convert it to a normal PR, get it reviewed and merged :)

**Comment by oSumAtrIX** [comment]
Please explain all changes in this PR. Why do you remove an enture code block, what do the additions do?

**Comment by OxrxL** [comment]
> Please explain all changes in this PR. Why do you remove an enture code block, what do the additions do?

I removed the entire code block because it generate conflicts during ads searching and suqsequently blocking.

But I prefer to close this PR because it is useless to further modify something that will be deprecated soon, 
in favor of a different patch.

**Pull request closed without merging**
