### PR TITLE
Reduce settings_fragment integrations length name

### PR DESCRIPTION
**Pull request by OxrxL**

### CODE REVIEW

**Comment by OxrxL** [comment]
@TheJeterLP

**Comment by oSumAtrIX** [comment]
What does this PR do?

**Comment by OxrxL** [comment]
> What does this PR do?

"Reduce the length name"

**Comment by OxrxL** [comment]
Just a filename simplification.

**Comment by oSumAtrIX** [comment]
This PR does not do anything.

**Comment by OxrxL** [comment]
> This PR does not do anything. Check your commits.

Wut? The commit shows me that the file is renamed.

Look at my fork.

**Comment by TheJeterLP** [comment]
You probably didn't merge upstream main to your fork

**Comment by OxrxL** [comment]
> You probably didn't merge upstream main to your fork

@oSumAtrIX pointed out the problem to me. Well...just rename the file as sculas show.

**Comment by TheJeterLP** [comment]
I don't see a reason for that. I kept the long name for a reason so that it's clear what that file is for

**Comment by OxrxL** [comment]
> I don't see a reason for that. I kept the long name for a reason so that it's clear what that file is for

Mhh...ok. Was just an idea to improve the name.

**Pull request closed without merging**
