### PR TITLE
feat(tiktok): signature spoof

### PR DESCRIPTION
**Pull request by d4rkk3y**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
To make this patch smaller, would it not be possible to patch the necessary call to the Android API? Right now you reflectively modify the call to it.

**Comment by d4rkk3y** [comment]
@oSumAtrIX did you mean only patch the call that cause the issue?

**Comment by oSumAtrIX** [comment]
No, this api is used in TikTok. Finding where and patching that would allow to get rid of the entire reflective workaround.

**Comment by d4rkk3y** [comment]
> No, this api is used in TikTok. Finding where and patching that would allow to get rid of the entire reflective workaround.

Ah I see. I will try that way. I hope TikTok did not call this api in native lib.

**Comment by oSumAtrIX** [comment]
Probably not, if they were reflection would've surely failed too.

**Comment by d4rkk3y** [comment]
Yes, If they check apk directly reflection will fail too. But if they call Android API from native lib it will not.

**Comment by oSumAtrIX** [comment]
What i meant, the reflection proxy succeeded, so it's likely not in a native library.

**Comment by d4rkk3y** [comment]
It seem TikTok don't not check signature use android api. I tested again and this did not work.

**Pull request closed without merging**
